import { appendFile, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { JsonValue } from "../core/types.ts";
import type { ArtifactWriter } from "../workflows/ports.ts";
import { redactJson } from "./redact.ts";

export const STATE_DIRECTORY = ".stanley";
export const ARTIFACT_ROOT = `${STATE_DIRECTORY}/runs`;
const GENERATED_IGNORE = "*\n!workflows/\n!workflows/**\n";

/**
 * Writes one run's artifacts under `.stanley/runs/<runId>`. Every value passes through the
 * redactor before it touches disk. Files are 0600 and directories 0700.
 */
export class Recorder implements ArtifactWriter {
  readonly directory: string;
  readonly relative: string;
  private chain: Promise<void> = Promise.resolve();

  private constructor(directory: string, relative: string) {
    this.directory = directory;
    this.relative = relative;
  }

  static async open(root: string, runId: string): Promise<Recorder> {
    await ensureStateDirectory(root);
    const relative = `${ARTIFACT_ROOT}/${runId}`;
    const directory = join(root, relative);
    await mkdir(directory, { recursive: true, mode: 0o700 });
    return new Recorder(directory, relative);
  }

  json(name: string, value: unknown): Promise<void> {
    return this.enqueue(async () => {
      const path = join(this.directory, name);
      const temporary = `${path}.tmp-${process.pid}`;
      await writeFile(temporary, `${JSON.stringify(sanitize(value), null, 2)}\n`, { mode: 0o600 });
      await rename(temporary, path);
    });
  }

  line(name: string, value: unknown): Promise<void> {
    return this.enqueue(() =>
      appendFile(join(this.directory, name), `${JSON.stringify(sanitize(value))}\n`, { mode: 0o600 }),
    );
  }

  flush(): Promise<void> {
    return this.chain;
  }

  private enqueue(operation: () => Promise<void>): Promise<void> {
    const next = this.chain.then(operation, operation);
    this.chain = next.catch(() => undefined);
    return next;
  }
}

/**
 * Create `<root>/.stanley` (0700) with its ignore file. Generated state (runs, improvements, candidates) stays
 * out of Git; only `workflows/` is committable.
 */
export async function ensureStateDirectory(root: string): Promise<string> {
  const directory = join(root, STATE_DIRECTORY);
  await mkdir(directory, { recursive: true, mode: 0o700 });
  await ensureIgnoreFile(join(directory, ".gitignore"));
  return directory;
}

async function ensureIgnoreFile(path: string): Promise<void> {
  try {
    await writeFile(path, GENERATED_IGNORE, { flag: "wx", mode: 0o600 });
    return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") return;
  }
  try {
    // Migrate only the exact file generated by builds before repository workflows existed.
    if ((await readFile(path, "utf8")) === "*\n") await writeFile(path, GENERATED_IGNORE, { mode: 0o600 });
  } catch {
    // Artifact recording must not replace or fail on a user-managed ignore file.
  }
}

function sanitize(value: unknown): JsonValue {
  const plain = JSON.parse(JSON.stringify(value ?? null)) as JsonValue;
  return redactJson(plain).value;
}
